### ISSUE TITLE
http: panic when sending gRPC hook

### ISSUE THREAD

**Issue by Clementp57** [tus/tusd#357]
**Describe the bug**
We are experiencing an error when tusd invokes the pre-create hook to our gRPC service.

**To Reproduce**
1. Execute command 'tusd -hooks-grpc <grpc_service_address> -hooks-enabled-events pre-create,post-create,post-finish [...]
2. Start upload using tus-js-client
3. See error :

``` 
[tusd] 2020/03/04 10:17:57 event="HookInvocationStart" type="pre-create" id=""
tusd_1      | 2020/03/04 10:17:57 http: panic serving 172.18.0.4:34116: runtime error: invalid memory address or nil pointer dereference
tusd_1      | goroutine 75 [running]:
tusd_1      | net/http.(*conn).serve.func1(0xc0002360a0)
tusd_1      |   /usr/local/go/src/net/http/server.go:1769 +0x139
tusd_1      | panic(0x10ae9e0, 0x1a33f30)
tusd_1      |   /usr/local/go/src/runtime/panic.go:522 +0x1b5
tusd_1      | github.com/tus/tusd/cmd/tusd/cli/hooks.GrpcHook.InvokeHook(0x7ffde7b79ed4, 0x19, 0x3, 0x1, 0x0, 0x0, 0x11c4a23, 0xa, 0x0, 0x0, ...)
tusd_1      |   /go/src/github.com/tus/tusd/cmd/tusd/cli/hooks/grpc.go:41 +0x224
tusd_1      | github.com/tus/tusd/cmd/tusd/cli.invokeHookSync(0x11c4a23, 0xa, 0x0, 0x0, 0x184ad0, 0x0, 0x0, 0xc00043e3c0, 0x0, 0x0, ...)
tusd_1      |   /go/src/github.com/tus/tusd/cmd/tusd/cli/hooks.go:143 +0x189
tusd_1      | github.com/tus/tusd/cmd/tusd/cli.preCreateCallback(0x0, 0x0, 0x184ad0, 0x0, 0x0, 0xc00043e3c0, 0x0, 0x0, 0x0, 0x0, ...)
tusd_1      |   /go/src/github.com/tus/tusd/cmd/tusd/cli/hooks.go:24 +0x80
tusd_1      | github.com/tus/tusd/pkg/handler.(*UnroutedHandler).PostFile(0xc000378410, 0x1425680, 0xc0004980e0, 0xc000420300)
tusd_1      |   /go/src/github.com/tus/tusd/pkg/handler/unrouted_handler.go:345 +0xf45
tusd_1      | net/http.HandlerFunc.ServeHTTP(0xc00037a380, 0x1425680, 0xc0004980e0, 0xc000420300)
tusd_1      |   /usr/local/go/src/net/http/server.go:1995 +0x44
tusd_1      | github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc00026c680, 0x1425680, 0xc0004980e0, 0xc000420300)
tusd_1      |   /go/src/github.com/bmizerany/pat/mux.go:117 +0x153
tusd_1      | github.com/tus/tusd/pkg/handler.(*UnroutedHandler).Middleware.func1(0x1425680, 0xc0004980e0, 0xc000420300)
tusd_1      |   /go/src/github.com/tus/tusd/pkg/handler/unrouted_handler.go:270 +0x8bc
tusd_1      | net/http.HandlerFunc.ServeHTTP(0xc00026c6a0, 0x1425680, 0xc0004980e0, 0xc000420300)
tusd_1      |   /usr/local/go/src/net/http/server.go:1995 +0x44
tusd_1      | net/http.StripPrefix.func1(0x1425680, 0xc0004980e0, 0xc000420200)
tusd_1      |   /usr/local/go/src/net/http/server.go:2034 +0x18d
tusd_1      | net/http.HandlerFunc.ServeHTTP(0xc00026ec90, 0x1425680, 0xc0004980e0, 0xc000420200)
tusd_1      |   /usr/local/go/src/net/http/server.go:1995 +0x44
tusd_1      | net/http.(*ServeMux).ServeHTTP(0x1a80960, 0x1425680, 0xc0004980e0, 0xc000420200)
tusd_1      |   /usr/local/go/src/net/http/server.go:2375 +0x1d6
tusd_1      | net/http.serverHandler.ServeHTTP(0xc0003785b0, 0x1425680, 0xc0004980e0, 0xc000420200)
tusd_1      |   /usr/local/go/src/net/http/server.go:2774 +0xa8
tusd_1      | net/http.(*conn).serve(0xc0002360a0, 0x1428c80, 0xc00026adc0)
tusd_1      |   /usr/local/go/src/net/http/server.go:1878 +0x851
tusd_1      | created by net/http.(*Server).Serve
tusd_1      |   /usr/local/go/src/net/http/server.go:2884 +0x2f4
```

**Expected behavior**
We expect the hook to be called on our gRPC service

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Windows 10 pro - Docker version 19.03.5, build 633a0ea
- Used tusd version: v1.1
- Used tusd data storage: S3 - minio inside docker container
- Used tusd configuration: 'tusd -s3-bucket tusd.upload -s3-endpoint http://host.docker.internal:9000 -hooks-grpc <grpc_service_address> -hooks-enabled-events pre-create,post-create,post-finish'
- Used tus client library: tus-js-client

**Comment by Acconut** [comment]
Thank you for reporting this! @inigohu Would it be possible for you to have a look at this report?
